name: d20-keras
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py36_0
  - astor=0.8.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.3.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.16.0=py36_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py36_0
  - jupyter_client=5.3.4=py36_0
  - jupyter_core=4.6.1=py36_0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py36_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.1=he1b5a44_1002
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libogg=1.3.2=h516909a_1002
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsndfile=1.0.28=he1b5a44_1000
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.5=h516909a_1002
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - openssl=1.1.1d=h7b6447c_4
  - pandas=1.0.1=py36h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.0.2=py36_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.2=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_1
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.15.7=py36h7b6447c_0
  - pysoundfile=0.10.2=py_1001
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.4.1=py36h0b6359f_0
  - send2trash=1.5.0=py36_0
  - setuptools=45.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tensorflow=1.14.0=gpu_py36h57aa796_0
  - tensorflow-base=1.14.0=gpu_py36h8d69cac_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_3
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - audioread==2.1.8
    - joblib==0.14.1
    - librosa==0.6.3
    - llvmlite==0.31.0
    - numba==0.48.0
    - resampy==0.2.2
    - scikit-learn==0.22.1
prefix: ## $your_user/anaconda3/envs/d20-keras

